"""Classes providing different types of initializers.

This module provides different types of initializers for SolrCMF problems.
It provides a class for random initialization and a class of initialization
from a previous run.
"""

from numpy import diag, flatnonzero, float64, s_, vstack, zeros_like
from numpy.linalg import qr
from numpy.random import Generator, default_rng
from numpy.typing import NDArray

from .base import Context, Entity, ViewDesc, constraint
from .blocks import SolrCMFBlocks, SolrCMFConstraints, SolrCMFParams


class RandomInitializer:
    """Randomly initialize the SolrCMF problem.

    A random initialization is generated as follows:
    - V matrices are generated by first generating p x max_rank
      matrices of standard normally distributed values.
      A QR decomposition is then performed and the p x max_rank
      matrix Q is used as the value for each V.
    - If factor sparsity is requested, U matrices are created as
      copies of the V matrices and Vp matrices are generated as
      zero matrices of the appropriate size. The corresponding
      Lagrange multipliers are initialized to zero.
    - D matrices are sampled entrywise from a uniform distribution
      on [-1, 1]
    - Z matrices are generated by multiplying the corresponding
      V and D matrices. The corresponding Lagrange multipliers
      are initialized to zero.
    """

    def __init__(self, rng: Generator | None = None):
        """Initialize a new RandomInitializer.

        Args:
            rng: An instance of `numpy.random.Generator`

        """
        if rng is None:
            rng = default_rng()

        self.rng = rng

    def __call__(
        self, ctx: Context[SolrCMFBlocks, SolrCMFConstraints, SolrCMFParams]
    ):
        """Generate random initial values for the SolrCMF problem.

        Args:
            ctx: a context for the SolrCMF problem.

        """
        for v in ctx.blocks.v.keys():
            ctx.blocks.v[v].value = qr(
                self.rng.standard_normal(ctx.blocks.v[v].shape)
            ).Q

            if ctx.params.factor_sparsity or ctx.params.fixed_factor_pattern:
                ctx.blocks.u[v].value = ctx.blocks.v[v].value.copy()

                ctx.blocks.vp[v].value = zeros_like(ctx.blocks.v[v].value)

                ctx.constraints.factor[v].value = zeros_like(
                    ctx.blocks.v[v].value
                )
                ctx.constraints.factor[v].residual = constraint(
                    ctx.constraints.factor[v], ctx
                )

        for k in ctx.blocks.d.keys():
            ctx.blocks.d[k].value = self.rng.uniform(
                -1.0, 1.0, ctx.blocks.d[k].shape
            )

            ctx.blocks.z[k].value = (
                ctx.blocks.v[k[0]].value
                @ diag(ctx.blocks.d[k].value)
                @ ctx.blocks.v[k[1]].value.T
            )

            ctx.constraints.mean_structure[k].value = zeros_like(
                ctx.blocks.z[k].value
            )
            ctx.constraints.mean_structure[k].residual = constraint(
                ctx.constraints.mean_structure[k], ctx
            )


class FromFormerInitializer:
    """Initializes from old context.

    Can perform extension to properly initialized state with factor
    sparsity even if the original object was run without.

    Can also reduce the rank of the former setup by removing all ranks
    which were zero across any DBlock.
    """

    def __init__(
        self,
        *,
        vs: dict[Entity, NDArray[float64]],
        ds: dict[
            ViewDesc,
            NDArray[float64],
        ],
        us: dict[Entity, NDArray[float64]] | None = None,
        reduce_max_rank: bool = False,
    ):
        """Initialize a new FromFormerInitializer.

        Args:
            vs: Factor matrices from a previous fit, one per view.
            ds: Scaling vectors from a previous fit, one per view pair.
            us: Sparse loading matrices from a previous fit, one per view.
                Required when the new problem uses factor sparsity or a fixed
                factor pattern.
            reduce_max_rank: If True, the effective rank is reduced to the
                number of globally active factors in the former solution (those
                non-zero in at least one d[k]) before copying the values.

        """
        self.vs = vs
        self.ds = ds
        self.us = us
        self.reduce_max_rank = reduce_max_rank

    def __call__(
        self, ctx: Context[SolrCMFBlocks, SolrCMFConstraints, SolrCMFParams]
    ):
        """Copy initial values from a previous solution.

        Args:
            ctx: a context for the current SolrCMF problem.

        """
        if self.reduce_max_rank:
            if ctx.params.fixed_factor_pattern:
                # if "structure_pattern" in ctx.params:
                structure_pattern = ctx.params.structure_pattern
            else:
                structure_pattern = {k: d != 0.0 for k, d in self.ds.items()}

            active_factors = flatnonzero(
                vstack(
                    [structure_pattern[k] for k in structure_pattern.keys()]
                ).sum(axis=0)
                != 0
            )

            if ctx.params.fixed_factor_pattern:
                # if "structure_pattern" in ctx.params:
                ctx.params.structure_pattern = {
                    k: p[active_factors]
                    for k, p in ctx.params.structure_pattern.items()
                }
            if ctx.params.fixed_structure_pattern:
                # if "factor_pattern" in ctx.params:
                ctx.params.factor_pattern = {
                    v: p[:, active_factors]
                    for v, p in ctx.params.factor_pattern.items()
                }
        else:
            active_factors = s_[:]

        for v in ctx.blocks.v.keys():
            ctx.blocks.v[v].value = self.vs[v][:, active_factors].copy()
            ctx.blocks.v[v].shape = ctx.blocks.v[v].value.shape

            if ctx.params.factor_sparsity or ctx.params.fixed_factor_pattern:
                if self.us is not None:
                    ctx.blocks.u[v].value = self.us[v][
                        :, active_factors
                    ].copy()
                    ctx.blocks.u[v].shape = ctx.blocks.u[v].value.shape

                    ctx.blocks.vp[v].value = (
                        ctx.blocks.u[v].value - ctx.blocks.v[v].value
                    )
                    ctx.blocks.vp[v].shape = ctx.blocks.vp[v].value.shape

                    ctx.constraints.factor[v].value = zeros_like(
                        ctx.blocks.v[v].value
                    )
                    ctx.constraints.factor[v].shape = ctx.constraints.factor[
                        v
                    ].value.shape
                    ctx.constraints.factor[v].residual = constraint(
                        ctx.constraints.factor[v], ctx
                    )

        for k in ctx.blocks.d.keys():
            ctx.blocks.d[k].value = self.ds[k][active_factors].copy()
            ctx.blocks.d[k].shape = ctx.blocks.d[k].value.shape

            ctx.blocks.z[k].value = (
                ctx.blocks.v[k[0]].value
                @ diag(ctx.blocks.d[k].value)
                @ ctx.blocks.v[k[1]].value.T
            )

            ctx.constraints.mean_structure[k].value = zeros_like(
                ctx.blocks.z[k].value
            )
            ctx.constraints.mean_structure[k].residual = constraint(
                ctx.constraints.mean_structure[k], ctx
            )
