[build-system]
requires = ["uv_build>=0.11.3,<0.12"]
build-backend = "uv_build"

[project]
name = "solrcmf"
description = "Tools for integrative analysis in flexible matrix layouts using penalized optimization techniques"
version = "0.2.0"
authors = [{ name = "Felix Held", email = "felix.held@gmail.com"}]
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.25",
    "joblib>=1.3.2",
    "scikit-learn>=1.1.0",
    "mkdocs-jupyter>=0.25.1",
]

[project.urls]
"Documentation" = "https://cyianor.github.io/solrcmf"
"Source" = "https://github.com/cyianor/solrcmf"
"Bug Tracker" = "https://github.com/cyianor/solrcmf/issues"

[dependency-groups]
dev = [
    "coverage>=7.10.7",
    "jupyter>=1.1.1",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.20",
    "mkdocstrings[python]>=0.30.0",
    "pandas>=2.3.2",
    "pytest>=8.4.2",
    "ruff>=0.15.9",
    "ty>=0.0.28",
]

[tool.hatch.version]
path = "src/solrcmf/__about__.py"

[tool.hatch.build.targets.sdist]
exclude = [
    "README.ipynb",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["I", "E", "F", "W", "D"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D"]
